spring.application.name=IRCTC-BackEnd

server.port=${PORT:8080}

# ============================================================
# RAILWAY MYSQL
# ============================================================

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata

spring.datasource.username=${MYSQLUSER}

spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ============================================================
# MYSQL CONNECTION
# ============================================================

spring.datasource.hikari.connectionTimeout=30000

spring.datasource.hikari.validationTimeout=5000

spring.datasource.hikari.initializationFailTimeout=120000

spring.datasource.hikari.maximumPoolSize=5

spring.datasource.hikari.minimumIdle=0


# ============================================================
# JPA / HIBERNATE
# ============================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ============================================================
# ERROR RESPONSE
# ============================================================

server.error.include-message=always